import React from "react";
import { Audio } from "@remotion/media";
import { linearTiming, TransitionSeries } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { slide } from "@remotion/transitions/slide";
import { wipe } from "@remotion/transitions/wipe";
import { AbsoluteFill, staticFile, useVideoConfig } from "remotion";
import { CtaScene } from "./scenes/CtaScene";
import { HookScene } from "./scenes/HookScene";
import { PackIntroScene } from "./scenes/PackIntroScene";
import { StepScene } from "./scenes/StepScene";
import { ValueScene } from "./scenes/ValueScene";
import { colors, TRANSITION } from "./theme";

// 30s square (1:1) Facebook / Instagram feed ad for the "Hair Growth 3-in-1" pack:
// derma roller + root-comb applicator bottle + scalp massage brush.
//
// Hook 0–4s → Pack 4–8s → Step 1 8–12s → Step 2 12–16s → Step 3 16–20s → Value 20–24s → Offer + CTA 24–30s
export const HairPackAd: React.FC = () => {
  const { fps } = useVideoConfig();
  const timing = linearTiming({ durationInFrames: TRANSITION });

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      <TransitionSeries name="Scenes">
        <TransitionSeries.Sequence
          name="Hook"
          durationInFrames={126}
          premountFor={fps}
        >
          <HookScene />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition
          presentation={wipe({ direction: "from-bottom" })}
          timing={timing}
        />
        <TransitionSeries.Sequence
          name="Pack intro"
          durationInFrames={132}
          premountFor={fps}
        >
          <PackIntroScene />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={timing}
        />
        <TransitionSeries.Sequence
          name="Step 1 · Derma roller"
          durationInFrames={132}
          premountFor={fps}
        >
          <StepScene
            step={1}
            title="ديرما رولر 540 إبرة"
            bullets={["ينشّط بصيلات الشعر", "يخلّي الزيت يدخل للجذور"]}
            howTo="مرّة في الجمعة على فروة الراس"
            products={[{ product: "dermaRoller", height: 260 }]}
            motion="roll"
            accent={colors.rose}
            background={colors.blush}
          />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={timing}
        />
        <TransitionSeries.Sequence
          name="Step 2 · Applicator"
          durationInFrames={132}
          premountFor={fps}
        >
          <StepScene
            step={2}
            title="قارورة بمشط للجذور"
            bullets={[
              "الزيت يوصل للجذور طول",
              "بلا تبذير و بلا وسخ",
              "بالوردي و إلا بالأكحل",
            ]}
            howTo="حطّي فيها الزيت متاعك و مشّطي"
            products={[
              { product: "bottlePink", height: 470 },
              { product: "bottleBlack", height: 470 },
            ]}
            motion="tilt"
            accent={colors.gold}
            background={`linear-gradient(160deg, ${colors.plumSoft} 0%, ${colors.plum} 100%)`}
            dark
          />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition
          presentation={slide({ direction: "from-right" })}
          timing={timing}
        />
        <TransitionSeries.Sequence
          name="Step 3 · Massage brush"
          durationInFrames={132}
          premountFor={fps}
        >
          <StepScene
            step={3}
            title="فرشة تدليك الراس"
            bullets={["تحرّك الدورة الدموية", "تنظيف عميق مع الشامبو"]}
            howTo="دقيقتين تدليك في الدوش"
            products={[{ product: "brushPink", height: 330 }]}
            motion="massage"
            accent={colors.rose}
            background={colors.blush}
          />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition presentation={fade()} timing={timing} />
        <TransitionSeries.Sequence
          name="Value stack"
          durationInFrames={132}
          premountFor={fps}
        >
          <ValueScene />
        </TransitionSeries.Sequence>
        <TransitionSeries.Transition
          presentation={wipe({ direction: "from-left" })}
          timing={timing}
        />
        <TransitionSeries.Sequence
          name="Offer + CTA"
          durationInFrames={186}
          premountFor={fps}
        >
          <CtaScene />
        </TransitionSeries.Sequence>
      </TransitionSeries>

      {/* Soundtrack (generated by scripts/generate-audio.mjs) */}
      <Audio
        name="Music"
        src={staticFile("audio/music.mp3")}
        volume={0.75}
        premountFor={fps}
      />

      {/* Whooshes on each cut (peak lands on the bar line) */}
      <Audio
        name="Whoosh → Pack"
        from={110}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Whoosh → Step 1"
        from={230}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Whoosh → Step 2"
        from={350}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Whoosh → Step 3"
        from={470}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.45}
        premountFor={fps}
      />
      <Audio
        name="Whoosh → Value"
        from={590}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Whoosh → CTA"
        from={710}
        src={staticFile("audio/whoosh.mp3")}
        volume={0.5}
        premountFor={fps}
      />

      {/* Accents: products landing, value rows, price */}
      <Audio
        name="Pop · roller lands"
        from={150}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Pop · bottle lands"
        from={165}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Pop · brush lands"
        from={180}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Shimmer · 3-in-1"
        from={195}
        src={staticFile("audio/shimmer.mp3")}
        volume={0.5}
        premountFor={fps}
      />
      <Audio
        name="Pop · row 1"
        from={615}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Pop · row 2"
        from={630}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Pop · row 3"
        from={645}
        src={staticFile("audio/pop.mp3")}
        volume={0.6}
        premountFor={fps}
      />
      <Audio
        name="Cash bell (price)"
        from={750}
        src={staticFile("audio/cash-bell.mp3")}
        volume={0.55}
        premountFor={fps}
      />
      <Audio
        name="Shimmer (end card)"
        from={840}
        src={staticFile("audio/shimmer.mp3")}
        volume={0.5}
        premountFor={fps}
      />
    </AbsoluteFill>
  );
};
