import React from 'react';
import {Audio} from '@remotion/media';
import {linearTiming, TransitionSeries} from '@remotion/transitions';
import {fade} from '@remotion/transitions/fade';
import {slide} from '@remotion/transitions/slide';
import {wipe} from '@remotion/transitions/wipe';
import {AbsoluteFill, staticFile, useVideoConfig} from 'remotion';
import {BenefitsScene} from './scenes/BenefitsScene';
import {CtaScene} from './scenes/CtaScene';
import {HookScene} from './scenes/HookScene';
import {ProductScene} from './scenes/ProductScene';
import {ProofScene} from './scenes/ProofScene';
import {SolutionScene} from './scenes/SolutionScene';
import {TRANSITION} from './theme';

// 30s square (1:1) Facebook / Instagram feed ad for NAWAR, a (fictional) Tunisian hair-care brand.
//
// Structure (AIDA):  Hook 0–4s → Solution 4–8s → Product 8–14s → Benefits 14–20s
//                    → Social proof 20–24s → Offer + CTA 24–30s
export const NawarAd: React.FC = () => {
	const {fps} = useVideoConfig();
	const timing = linearTiming({durationInFrames: TRANSITION});

	return (
		<AbsoluteFill style={{backgroundColor: 'black'}}>
			<TransitionSeries name="Scenes">
				<TransitionSeries.Sequence name="Hook" durationInFrames={126} premountFor={fps}>
					<HookScene />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={wipe({direction: 'from-bottom'})} timing={timing} />
				<TransitionSeries.Sequence name="Solution" durationInFrames={132} premountFor={fps}>
					<SolutionScene />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={fade()} timing={timing} />
				<TransitionSeries.Sequence name="Product" durationInFrames={192} premountFor={fps}>
					<ProductScene />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={slide({direction: 'from-right'})} timing={timing} />
				<TransitionSeries.Sequence name="Benefits" durationInFrames={192} premountFor={fps}>
					<BenefitsScene />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={slide({direction: 'from-bottom'})} timing={timing} />
				<TransitionSeries.Sequence name="Social proof" durationInFrames={132} premountFor={fps}>
					<ProofScene />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={wipe({direction: 'from-left'})} timing={timing} />
				<TransitionSeries.Sequence name="Offer + CTA" durationInFrames={186} premountFor={fps}>
					<CtaScene />
				</TransitionSeries.Sequence>
			</TransitionSeries>

			{/* Soundtrack (generated by scripts/generate-audio.mjs) */}
			<Audio name="Music" src={staticFile('audio/music.mp3')} volume={0.75} premountFor={fps} />

			{/* Whooshes on each cut (peak lands on the bar line) */}
			<Audio name="Whoosh → Solution" from={110} src={staticFile('audio/whoosh.mp3')} volume={0.5} premountFor={fps} />
			<Audio name="Whoosh → Product" from={230} src={staticFile('audio/whoosh.mp3')} volume={0.4} premountFor={fps} />
			<Audio name="Whoosh → Benefits" from={410} src={staticFile('audio/whoosh.mp3')} volume={0.5} premountFor={fps} />
			<Audio name="Whoosh → Proof" from={590} src={staticFile('audio/whoosh.mp3')} volume={0.5} premountFor={fps} />
			<Audio name="Whoosh → CTA" from={710} src={staticFile('audio/whoosh.mp3')} volume={0.5} premountFor={fps} />

			{/* Accents */}
			<Audio name="Shimmer (reveal)" from={240} src={staticFile('audio/shimmer.mp3')} volume={0.6} premountFor={fps} />
			<Audio name="Pop · benefit 1" from={435} src={staticFile('audio/pop.mp3')} volume={0.6} premountFor={fps} />
			<Audio name="Pop · benefit 2" from={465} src={staticFile('audio/pop.mp3')} volume={0.6} premountFor={fps} />
			<Audio name="Pop · benefit 3" from={495} src={staticFile('audio/pop.mp3')} volume={0.6} premountFor={fps} />
			<Audio name="Cash bell (price)" from={750} src={staticFile('audio/cash-bell.mp3')} volume={0.55} premountFor={fps} />
			<Audio name="Shimmer (end card)" from={840} src={staticFile('audio/shimmer.mp3')} volume={0.5} premountFor={fps} />
		</AbsoluteFill>
	);
};
